### ISSUE TITLE
Publishing does not outbid existing claims

### ISSUE THREAD

**Issue by stoatally** [lbryio/spee.ch#10]
Currently when you publish a new image with a name matching an existing claim, it does not outbid that claim and the publish process continues as though it has worked correctly.

It should either:

1) Outbid any existing claims (who pays?)
2) Complain to the uploader that the claim is taken.

I'm curious if named claims are really the best way forward, it sure is cool to be able to name your image, but is it practical to implement it that way, and does it solve any real world problem?

**Comment by kauffj** [comment]
100% agreed. I think spee.ch should support claim based resolution like:

[https://spee.ch/doitlive#claimID](https://spee.ch/doitlive#claimID)

By doing partial claim ID matches, these can be really short like: `https://spee.ch/doitlive#b`

Then the named URLs can remain.

(I used anchors above because that's how the LBRY URI schema is defined currently, but that anchor sure is inconvenient for HTTP access...)

**Comment by stoatally** [comment]
If we're talking about naming, we should also consider how we want to handle thumbnailing/resizing. If you are uploading an image to share on a forum you might get into trouble for including a massive image inline, so giving people the option for a couple of image size presets would be handy.

Can you feel the scope growing?

**Comment by billbitt** [comment]
This is a great issue @stoatally.  I was just thinking about this a couple days ago and great to see it was already discussed.  I agree with @kauffj that we can provide a specific claim ID url for spee.ch uploads (currently 'spee.ch/name/claim_id') while leaving 'spee.ch/claim' for the highest bidder (Or some other algorithm.  Perhaps largest bidder with time since bidding as a factor?).

Re providing sizing etc.  I think that's a great idea.  perhaps we could use a third "/" to denote a size. e.g. 'spee.ch/name/claim_id/small', 'spee.ch/name/claim_id/medium', etc.

**Comment by kauffj** [comment]
For true sexiness: spee.ch/name/claim_id/450x200 ;)

**Comment by kauffj** [comment]
Splitting this into separate tickets.
