### ISSUE TITLE
Publishing to a channel gives incorrect implications about content locations

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#177]
When publishing via spee.ch to a channel that has competing claims, I am shown a URL that does not actually work to access my content.

E.g. when creating the @lbry channel on spee.ch, I am shown that a piece of content will have the following URL: spee.ch/@lbry/lbryintro.mp4

Since there are competing claims for @lbry and the spee.ch channel claim was not winning, the actual URL was: spee.ch/@lbry:3f/lbryintro.mp4

**Comment by billbitt** [comment]
I updated the URL preview to include the channel's short id, if a channel is selected.  However, this is still an issue for publishes with no channel.  Since the publish has been made yet, it is not possible to tell the user what their claim id will be in the URL preview.  We may need to think of a way to account for this so users are not dissapointed when their content is not actually available at `spee.ch/example.mp4` but instead at `spee.ch/xyz/example.mp4`
