### ISSUE TITLE
Channel pages are missing proper meta descriptions

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#178]
See: https://www.facebook.com/lbryio/posts/1866472090336219

**Comment by MSFTserver** [comment]
what should it be saying? my last PR that i closed to clean it up i added some facebook and twitter cards to the metadata that might have what your looking for

**Comment by MSFTserver** [comment]
currently the meta descriptions for channel pages are set to:
```
<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="@lbryio">
<meta property="og:title" content="spee.ch">
<meta property="og:site_name" content="spee.ch">
<meta property="og:type" content="website">
<meta property="og:image" content="https://spee.ch/assets/img/content-freedom-64px.png">
<meta property="og:url" content="http://spee.ch/">
<meta property="og:description" content="Open-source, decentralized image and video hosting.">
```

**Comment by kauffj** [comment]
A few of these are wrong:

`og:url` should be spee.ch/@channel (right?)
`og:description` should be something referencing the channel. Maybe something like "Free images and videos published by @channel". This could still be better.
`og:title` should just be @channel or "@channel on spee.ch"

I'm not sure what `twitter:site` should be.

**Comment by MSFTserver** [comment]
yea i can fix this in my next PR that adds social charing buttons since this would tie into the facebook share button ill do this after billbit does some css changes he told me to hold off on my old PR and i want to clean it up a lot.

about the twitter stuff i think i have proper cards setup for this instance already just need to test it while its live for sizing and some other things that are clearly described or usage example in twitter dev docs,
for the `twitter:site` that should be the twitter account name for the provider like `@speech` or `@lbryio` on twitter, heres where i added twitter cards all fields are correct formatted except the video post functions https://github.com/lbryio/spee.ch/pull/158/commits/d2c4ce8b923cdccc2b94cb7e019693f9daee3209
all the meta data description and site stuff we want to be linked to provider site for twitter 

i can change it up a little with suggestions you have for description and title ect. shouldnt be hard just twitter has to be live to test not sure if facebook has a test option since twitter discontinued there offline tester thing

**Comment by MSFTserver** [comment]
reference:
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/player-card

https://developers.facebook.com/docs/sharing/webmasters
