### ISSUE TITLE
Spee.ch should use chainquery for the relational database

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#455]
<<Still need to determine a path for this, Please define and document >>

Spee.ch relies on a relational database version of the LBRY blockchain data, so that it can search for available claims, metadata, etc.

Spee.ch currently uses https://github.com/billbitt/spee.ch-sync to sync the data from lbry blocks into a mysql database.  Spee.ch should be updated to use https://github.com/lbryio/chainquery

**Comment by skhameneh** [comment]
I've been going over this; it was suggested we make the existing chainquery instance a master to Spee.ch as a slave.  In my findings this can only be done with an explicit slave defined within the master (as well as the master defined on the slave).

My notes on the Master/Slave model:
- This promotes having read-only slave data mixed with local instance data.
- Requires the master to maintain explicit information about all slaves.
- Likely won't be a common implementation for most external (from LBRY Inc) deployments.
- Eliminates the need to run another `lbrycrd` instance (aside from the existing chainquery instance) and the need to run a local `chainquery` daemon.

Read-only remote MySQL access for all `chainquery` queries:
- Read-only scaling becomes a responsibility of `chainquery` rather than scaling slaves for Spee.ch that must be configured in the master `chainquery` instance.
- Spee.ch instances don't need to be concerned with master/slave sync status.
- Remote database access is optional; `chainquery` can be configured within the same instance.
- For `chainquery`, tools like MySQL proxy exist for easily handling load balancing when it becomes necessary.  Load balancing for chainquery is not required but will be readily available with no changes necessary for any Spee.ch instances.

**Comment by kauffj** [comment]
@skhameneh are you proposing all spee.ch instances connect to the same chainquery instance?

Setting aside questions as to whether this is against the vision of spee.ch/LBRY, wouldn't this cause performance issues since you're repeatedly going across the internet to return a request?

**Comment by skhameneh** [comment]
For the vision, having a SQL slave is not decentralized, it's an unnecessary complexity and introduces additional fragility.  If we want Spee.ch completely detached from LBRY, it should have it's own maintained instance of `chainquery`.  I highly advise we keep this simple.

**Comment by tiger5226** [comment]
I think for read only queries, MySQL is very powerful. I think we are far from having to scale chainquery. I do not think the traffic of spee.ch will drag down the performance of the chainquery instance. We can easily increase the hardware specs if there is even a problem. How many queries per second are we talking about? If it will be more than 10-20 per second We may want to add another CPU or 2 depending on the query. I think a good idea for uptime is to have two instances of chainquery with a load balancer so that we can upgrade 1 while the other still serves requests and then do the other.

Keeping it simple until there is a problem is a good idea. Also having a separately maintained instance of chainquery for the spee.ch servers seems like overkill. We are barely using the production chainquery instance right now. It has way more bandwidth available that we think.

I don't see a reason to complicate the architecture if it is not needed. I may be completely wrong and we are actually seeing the potential for TONS of queries. 

My concerns about performance are there but they can be overlooked by just changing the mysql configuration every time we want to do bulk processing with a migration. 99.999% of the queries against the db are read-only anyway. So almost ALL of the traffic can be concurrent. It supports 150 concurrent connections by default and as I say above we have plenty of room to increase the hardware specs to support high concurrency.

**Comment by skhameneh** [comment]
Note: The `channel` table cannot be dropped because there is no way to query what channels are controlled by Spee.ch without it.  **We may want to drop `channelName` from the `channel` table to discourage using sources other than chainquery to get channel names** throughout Spee.ch; this can allow all channels (channels that are not managed by Spee.ch) to load within Spee.ch.

We need to have a wider discussion about this, but it is not high priority.  All my changes favor data in `chainquery` over the Spee.ch tables.

**Comment by skhameneh** [comment]
Merged https://github.com/lbryio/spee.ch/issues/591 & closed https://github.com/lbryio/spee.ch/issues/590, these gave me issues while running tests against my code independent of Webpack (some of the plugins/presets used by Spee.ch broke `babel-cli`)

**Comment by lyoshenka** [comment]
Where did we land on this? My first instinct is to have each speech server run its own local instance of chainquery. This seems to be the simplest solution. Is that what you're leaning towards?

**Comment by skhameneh** [comment]
@tiger5226 and I both agreed connecting to the existing chainquery instance would be easiest.
@kauffj has suggested to make the Spee.ch MySQL a slave of the existing chainquery instance but that would require `binlog` to be enabled on the `chainquery` master to which Mark claimed would be a major perf issue (re-syncs could take a week).

`chainquery` could be ran locally, but then we'd have to have more jobs running to monitor its health - as well as additional resource consumption.  Nobody has pushed for that approach.  Do you want to discuss this further tomorrow?  From a code perspective I am writing separate configs for `chainquery` within Spee.ch, this gives us full flexibility switch between any of these implementations.

See https://github.com/lbryio/spee.ch/pull/593

**Comment by tiger5226** [comment]
The only concern I have with multiple instances of chainquery is continuous delivery, although I also just don't think it is necessary we are barely using the chainquery instance right now and I have no reason to believe that it could not handle the load from speech right now. However, thinking about it some more as long as you have the automatic update api exposed, I can just add the instances to the travis.yml file to make sure they all get updated automatically.
