### ISSUE TITLE
spee.ch should set a publish address and change address by rotating through a pool of addresses

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#469]
@shyba proposed this fix as a way to improve publish times.
@kauffj has raised the issue that this should perhaps be solved at the daemon layer.

**Comment by kauffj** [comment]
I'm not 100% that this should be at daemon layer, I was hoping to see approach described in some more detail to get a sense of the appropriateness.

I was also curious to understand what the "real" fix might be. At first, we stopped using too many addresses because that hurt performance. Now it turns out using too few addresses also hurts performance!

Is it a hard requirement that all large cases will have to hit this sweet spot? Or are there other improvements that could make this work with larger or smaller numbers of addresses?

**Comment by shyba** [comment]
That's just a temporary workaround. The right way to do it is to have a set of address on the daemon and distribute over them, which is what happens by default, but the current implementation is absurdly slow for large wallets. The new wallet should do this automatically and can be further improved to beyond that, but for now it's not worth fixing in lbryum as it will be phased out.
As an even simpler workaround, manually setting another address and making the current one to the secondary list (configuration change) should do it until the new wallet gets released. Another workaround is setting the change address. Anyway, I would recommend doing this only if its quick and test first as a configuration change to see if its worth a code change. On the long run its better to have this fixed on the daemon and there is an issue to track performance progress on the new implementation for this case: https://github.com/lbryio/lbry/issues/1219

**Comment by kauffj** [comment]
:+1: thanks for clarity @shyba

**Comment by kauffj** [comment]
@shyba and/or @eukreign is there a ticket for lbry that explains what needs to be fixed for spee.ch to not need to do this? If not, can you create one and link it here?

**Comment by shyba** [comment]
I would say https://github.com/lbryio/lbry/pull/1155 but maybe @eukreign can point a more specific one. I believe the new wallet solves it by doing sane queries instead of full listing loops and had that issue in mind since the initial design. I think lex also found an issue with the number of times an address is supposed to be used on the current wallet.

**Comment by kauffj** [comment]
So when lbryio/lbry#1155 is closed, this change would no longer be necessary?

I'm more inclined to wait if that's the case @billbitt

**Comment by kauffj** [comment]
Although realistically I bet that's a month out

**Comment by shyba** [comment]
Just to highlight the origin so we don't get lost: Keep in mind that the performance gain of this hack may not be worth the code changes. Running a quick test publish over a fixed new clean address should give a more realistic estimate. This came up from the publishing experiments which you can see here: https://hackmd.io/s/BkDE20d17
From the chart, the check for if a name was already claimed looks like the heaviest. So if it looks too hacky or brings technical debt I would definitely wait for it to be solved on the daemon.

**Comment by shyba** [comment]
Ideally, if spee.ch can change the main address config without any impact I guess that would be best than coding a workaround. Then we can revert the config, which looks less impacting.

**Comment by shyba** [comment]
Another reason not to pursue at speech code level at all is that the improvement is around 16%. It could be more on speech since this address history is huge, but we need to test before any other larger step. If confirmed, maybe a configuration change could be done. If bigger than expected, then we think of alternatives.

**Comment by billbitt** [comment]
@shyba when this is 'fixed' in the daemon, will it only publish from a select amount of addresses and how does that address pool get decided?
Currently, one benefit of spee.ch setting its own publish bid address is that it can then look at the table of claims records and identify which records were published from this wallet by using that address.  It sounds like this may not be a scalable/long term way of doing things, especially if spee.ch will publish from many wallet addresses.  Alternatively, spee.ch could add a column to the table or keep a separate table to track which claims are its publishes.

**Comment by shyba** [comment]
I think we could modify `publish` to return the chosen address to so you can store it. However, if its expected to come from a configured known list I think we would need to revisit that by finding an alternative approach, like a new column as you suggested.

**Comment by billbitt** [comment]
I am closing this issue as it sounds like it is an unnecessary app-level patch when the issue should be solved by the new wallet
