### ISSUE TITLE
Allow Editing

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#482]
Let me change the metadata or even the file itself.

**Comment by skhameneh** [comment]
After talking to Bill, need to clarify if edits will update an existing claim or just create a brand new claim with old data pre-populated (as you and I previously discussed)

**Comment by tzarebczan** [comment]
Preferably it would be an update to the claim. The claim id is part of the short URL for my content, so unless you create a redirect, you'd want this to stay the same. The old claim would still need to be abandoned if we decided to make a new claim  - so that's 2 transactions instead of 1. 

I would assume this would only be possible on authenticated channels, unless we introduce a new feature where we give the user an option to specify an "edit password" when publishing.
