### ISSUE TITLE
Thumbnail not showing in LBRY app, uploaded through API

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#515]
Not sure what happened recently, but thumbs uploaded through the API via the LBRY app are not showing: lbry://channelloading3#1df0789a9c66948a5535fe0c72dc0ce1acc2c97c

"thumbnail": "https://spee.ch/003405a6996d5ede33778367017aa25a2d117924/8ldohtO05Gx0UlwicejtY4nD.jpg"

Update: only seems to happen if you click "view file" after thumb upload.

**Comment by tzarebczan** [comment]
When uploaded through spee.ch directly and copied direct URL - that worked.

**Comment by tzarebczan** [comment]
The original thumb started working, possibly after spee.ch was restarted. 

I did publish a new one, and it's broken: 
"thumbnail": "https://spee.ch/0fd1e24f4c637ee5e4b583283e87a3df547e0b9f/XbEiSLKp4uUH8EBefD5lzc6y.jpg (28 kB)

Claim: lbry://mdfile#24e737e03df62930ac4bd44151c818b3933a0381

**Comment by tzarebczan** [comment]
The above is now working and I tried a new publish/thumb that's also working.

**Comment by tzarebczan** [comment]
Actually, it's still happening..maybe my steps weren't exactly the same. It works correctly if you don't view the file at the URL (i.e. https://spee.ch/79fad4af048f1b03abf238a9ae411df054f2e129/b6zgDCUnboKv8Pz3irozZm5X.jpg) - the app gives this URL to view the thumb after upload. If you do click that link, then it doesn't show as a thumb. If you don't click it, it shows as a thumb. 

What's strange is that if you go to the long URL after it's published, it still shows as a thumb. 

Sample of broken on here now: lbry://jpgfile#7cf810f50a709b15fe5f7da591cbf9620902f122

**Comment by kauffj** [comment]
Odds this is just #507?

**Comment by tzarebczan** [comment]
@kauffj might be somewhat related, but in this case, the image does show correctly (jpgs always uploaded), but the thumb doesn't.

**Comment by billbitt** [comment]
This definitely sounds like cloudflare.  Same issue as #507 but will require a different solution.
Sounds like problem is: user is visiting the url to view their image, triggering cloudflare to cache the html document response, and then when the app requests the thumb from the same link cloudflare serves the document instead of the image/video.
One solution would be to change the app's code so that it uses the `https://spee.ch/asset/<claim name>/<claim id>` spee.ch url format for thumbs.  This is what we did to fix the issue on spee.ch.  I like this solution, but it fixes it for our use cases while keeping the confusing behavior for others.  I.e. other spee.ch users who try to view a link on spee.ch and then embed that same link will run into this same problem.  If we go this route, we should specifically spell out to our users that there are now two urls: an embed url and a view url.
Another approach would be to work on cloudflare (or alternatives) and find a way to stop it from caching responses for these urls so that spee.ch can continue to make the decision of whether to serve the html document or an image.  
Thoughts @skhameneh ?
