### ISSUE TITLE
is there any javascript api implemetation of crul publish, images

### ISSUE THREAD

**Issue by yashwanth2804** [lbryio/spee.ch#524]

**Comment by tzarebczan** [comment]
Not that I know of (@billbitt ?), would you be interested in creating one?

**Comment by billbitt** [comment]
Hi @yashwanth2804 are you looking for examples of how to publish via the api with javascript?  
Here are two examples:
- in spee.ch's front end code: https://github.com/lbryio/spee.ch/blob/master/client/src/sagas/publish.js
  - note: this is done in a redux saga.  
  - line 36 is where the saga creates the `form` data to send with the request https://github.com/lbryio/spee.ch/blob/master/client/src/sagas/publish.js#L36
  - line 38 for where the saga creates a `channel` to make the request. https://github.com/lbryio/spee.ch/blob/master/client/src/sagas/publish.js#L38  The purpose of this `channel` is so that the saga can emit actions as it receives updates on the request.
  - here is the `channel` where the request is actually made via `XMLHttpRequest`.  This is probably what you are looking for.  Note that it takes in the prepared form data as an argument.
- in the lbry desktop app: 
  - here is where the app makes a publish request for thumbnails.  Note it uses `fetch`: https://github.com/lbryio/lbry-desktop/blob/master/src/renderer/redux/actions/publish.js#L108
