### ISSUE TITLE
Transpile on build and do not check in compiled assets

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#537]
The content https://github.com/lbryio/spee.ch/pull/536 of looks like something that should not be checked in. Also, if that's generated manually, it can presumably be added to CI.

**Comment by billbitt** [comment]
agreed.  The reason it is getting checked in now is because www.spee.ch uses spee.ch as a package and the package code needs to be transpiled.  I'm planning to combine the two repos because the original reason for splitting them is no longer necessary and it will be simpler with one repo.  https://github.com/lbryio/spee.ch/issues/516
