### ISSUE TITLE
Should publish API require a claim name?

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#547]
If we are requiring a claim name on the spee.ch publish API, it should be clear that the name should contain some unique characters since we only support publishing to a single claim name (not sure how long we'll have this limitation, issue is filed on the daemon).  This should also be the case if it's optional - someone won't know that until it fails to publish. Or maybe the solution is to tack on a `-1`/ `-2` automatically?

**Comment by billbitt** [comment]
If a claim name is provided, we shouldn't change that claim while publishing because the request might be depending on getting that exact claim name back.  I think giving them an error message is preferred.  However, we could add a way for them to opt in to allowing spee.ch to change the claim name (perhaps an optional `strict` parameter which can be set to `false` ).

I do agree that the claim name should be optional though, and if not provided spee.ch generates a random hash for the name.

**Comment by alyssaoc** [comment]
@tzarebczan Is this issue still valid?

**Comment by alyssaoc** [comment]
closing, reopen if necessary
