### ISSUE TITLE
PSR-1 Basic Coding Standard

### ISSUE THREAD

**Issue by stoatally** [lbryio/spee.ch#7]
Just something to get out of the way as early as possible, it would be nice to follow these coding standards for PHP as they are quite widely used, especially by composer packages.

http://www.php-fig.org/psr/psr-1/

**Comment by billbitt** [comment]
since we are moving to a js implementation and this suggestion is for PHP I am going to close this issue, but feel free to open a new one particular to js coding standards.  However, please do note that this is very much an alpha build at the moment so there are a lot of console logs and intermixed use of single vs. double quotes that I am aware need to be fixed.
