### ISSUE TITLE
Normalization Hardfork - Changes required

### ISSUE THREAD

**Issue by skhameneh** [lbryio/spee.ch#808]
https://github.com/lbryio/spee.ch/issues/618

Verify local table claims follow the correct normalization while they are pending

**Comment by tiger5226** [comment]
In order to support the changes, and searches performed on behalf of users of spee.ch need to be normalized. spee.ch needs to implement NFD normalization so queries sent to Chainquery properly compare claim names. There will be two columns now `name`, and `normalized_name` for the vanity name and normalized name respectively.

**Comment by tiger5226** [comment]
I spoke with @lyoshenka about this and we agreed on the following:

Research Results:

- lbrycrd is using ICU  v57.1 for normalization which supports UCA 8.0
- mysql v5.7 supports UCA 4.0 and 5.2
- mysql v.8.0 supports UCA 4.0, 5.2 and 9.0 
- NFD/NFC are formations(presentation) which will be provided by lbrycrd already.

Solution:

- Upgrade Chainquery DB to MySQL 8.0 to leverage UCA 9.0
- There are differences in support between UCA 8.0 and UCA 9.0 that could cause issues but we will cross that bridge when it comes. 

Summary:

The only way for lbrycrd and DBMS solutions to align on unicode would be for UCA 9.0. This would require @BrannonKing to upgrade the boost libraries for lbrycrd and to use ICU v58.2. This is not ideal and the extra work does not have good reasoning since we cannot predict any REAL issues with UCA support ( off by 1 version ). Keeping the changes to Chainquery will allow all other services to not have to make any changes.
