### ISSUE TITLE
Add support for more video (file) types

### ISSUE THREAD

**Issue by elmcrest** [lbryio/spee.ch#916]
Hey all,

just wanted to leave this here for your further consumption :)

I've just tried to share a .mov video file with spee.ch but it didn't pass the validation.

![telegram-cloud-file-2-255433998-303428-5986550462190132941](https://user-images.githubusercontent.com/931919/52792969-ec442180-306c-11e9-95ac-92ce06d72b02.jpg)

there are of course more formats, like .avi or several more - I'm not a video expert so I can't really help more on this.

though something to keep in mind is that the filename extension isn't something you can rely on - like a .avi file could have a video with h264, h265 or some complete different codec.

**Comment by tzarebczan** [comment]
Hey @elmcrest , thanks for opening the issue! To provide the fastest and best experience, we do recommend web optimized mp4s since these can be streamed as soon as the file starts downloading, as opposed to other types of videos where they need to be downloaded in their entirety. Not sure we'll support others as is here on spee.ch, but we will consider automatically converting them via our LBRY SDK (I've been meaning to file a feature request around this).

**Comment by tzarebczan** [comment]
@elmcrest , this is now possible on spee.ch. We still have to do some work on making these files actually playable, but any file type can now be uploaded.
